staticDir = ["static"]
baseURL = "https://gavinfowler.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "Gavin Fowler"
[params]
    disqusShortname = ""
    googleAnalytics = ""
    layoutReverse = true
    theme = "hyde"
    themeColor = "black"
    textColor = "#ffffff"
    description = "Software engineer, Gaming enthusiast, Amateur Curler, Musician"
    main = [
        {Name = "About", URL = "/about", Newpage = 0 },
        {Name = "My Resume", URL = "/static/resume.pdf", Newpage = true},
        {Name = "Github", URL = "https://github.com/gavinfowler", Newpage = true},
    ]